// AUTO-GENERATED by scripts/fetch-sport-images.mjs — do not edit by hand.
import { ImageSourcePropType } from 'react-native';

export const sportImages: Record<string, ImageSourcePropType> = {
  'karate': require('../../assets/sports/karate.jpg'),
  'boxing': require('../../assets/sports/boxing.jpg'),
  'muay-thai': require('../../assets/sports/muay-thai.jpg'),
  'taekwondo': require('../../assets/sports/taekwondo.jpg'),
  'mma': require('../../assets/sports/mma.png'),
  'krav-maga': require('../../assets/sports/krav-maga.png'),
  'capoeira': require('../../assets/sports/capoeira.jpg'),
  'kung-fu': require('../../assets/sports/kung-fu.jpg'),
  'bjj': require('../../assets/sports/bjj.jpg'),
  'judo': require('../../assets/sports/judo.jpg'),
  'wrestling': require('../../assets/sports/wrestling.jpg'),
  'aikido': require('../../assets/sports/aikido.jpg'),
  'fencing': require('../../assets/sports/fencing.jpg'),
  'archery': require('../../assets/sports/archery.jpg'),
  'running': require('../../assets/sports/running.jpg'),
  'swimming': require('../../assets/sports/swimming.jpg'),
  'cycling': require('../../assets/sports/cycling.jpg'),
  'rowing': require('../../assets/sports/rowing.jpg'),
  'triathlon': require('../../assets/sports/triathlon.jpg'),
  'powerlifting': require('../../assets/sports/powerlifting.jpg'),
  'gymnastics': require('../../assets/sports/gymnastics.jpg'),
};
