// AUTO-GENERATED by scripts/fetch-sport-images.mjs — do not edit by hand.
//
// 520px versions of the same photos, for the home grid. The full-size
// originals decode at ~1000px no matter how small they are drawn, which
// made scrolling the grid stutter; the sport page hero still uses those.
import { ImageSourcePropType } from 'react-native';

export const sportThumbs: Record<string, ImageSourcePropType> = {
  'karate': require('../../assets/sports/thumbs/karate.jpg'),
  'boxing': require('../../assets/sports/thumbs/boxing.jpg'),
  'muay-thai': require('../../assets/sports/thumbs/muay-thai.jpg'),
  'taekwondo': require('../../assets/sports/thumbs/taekwondo.jpg'),
  'kickboxing': require('../../assets/sports/thumbs/kickboxing.jpg'),
  'mma': require('../../assets/sports/thumbs/mma.png'),
  'krav-maga': require('../../assets/sports/thumbs/krav-maga.png'),
  'capoeira': require('../../assets/sports/thumbs/capoeira.jpg'),
  'kung-fu': require('../../assets/sports/thumbs/kung-fu.jpg'),
  'bjj': require('../../assets/sports/thumbs/bjj.jpg'),
  'judo': require('../../assets/sports/thumbs/judo.jpg'),
  'wrestling': require('../../assets/sports/thumbs/wrestling.jpg'),
  'aikido': require('../../assets/sports/thumbs/aikido.jpg'),
  'fencing': require('../../assets/sports/thumbs/fencing.jpg'),
  'kendo': require('../../assets/sports/thumbs/kendo.jpg'),
  'archery': require('../../assets/sports/thumbs/archery.jpg'),
  'running': require('../../assets/sports/thumbs/running.jpg'),
  'swimming': require('../../assets/sports/thumbs/swimming.jpg'),
  'cycling': require('../../assets/sports/thumbs/cycling.jpg'),
  'rowing': require('../../assets/sports/thumbs/rowing.jpg'),
  'triathlon': require('../../assets/sports/thumbs/triathlon.jpg'),
  'powerlifting': require('../../assets/sports/thumbs/powerlifting.jpg'),
  'olympic-weightlifting': require('../../assets/sports/thumbs/olympic-weightlifting.jpg'),
  'crossfit': require('../../assets/sports/thumbs/crossfit.jpg'),
  'gymnastics': require('../../assets/sports/thumbs/gymnastics.jpg'),
  'yoga': require('../../assets/sports/thumbs/yoga.jpg'),
  'soccer': require('../../assets/sports/thumbs/soccer.jpg'),
  'basketball': require('../../assets/sports/thumbs/basketball.jpg'),
  'tennis': require('../../assets/sports/thumbs/tennis.jpg'),
  'volleyball': require('../../assets/sports/thumbs/volleyball.jpg'),
  'baseball': require('../../assets/sports/thumbs/baseball.jpg'),
  'rugby': require('../../assets/sports/thumbs/rugby.jpg'),
  'golf': require('../../assets/sports/thumbs/golf.jpg'),
  'badminton': require('../../assets/sports/thumbs/badminton.jpg'),
  'climbing': require('../../assets/sports/thumbs/climbing.jpg'),
  'hiking': require('../../assets/sports/thumbs/hiking.jpg'),
  'surfing': require('../../assets/sports/thumbs/surfing.jpg'),
  'skiing': require('../../assets/sports/thumbs/skiing.jpg'),
  'snowboarding': require('../../assets/sports/thumbs/snowboarding.jpg'),
  'skateboarding': require('../../assets/sports/thumbs/skateboarding.jpg'),
};
